source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.2"
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end



# -------------------------------- 追加 --------------------------------

gem 'discard'              # soft delete
gem 'rails-i18n'           # i18n拡張

gem 'dotenv-rails'         # 環境変数を.envで管理
gem 'devise'               # 認証機能。パワフルだが拡張に難あり
gem 'devise-i18n'          # deviseの日本語化
gem 'devise-jwt'           # 認証機能.　Devise＋APIの場合
gem 'pundit'               # 認可
# gem "jwt"                # JSON Web Token認証機能. API認証自前実装の場合
# gem "rack-cors"          # SPAの場合.外部からのリクエストを許可
# gem "bcrypt"             # 暗号化 deviseを使う場合は含まれている
# gem 'ActiveAdmin'        # 管理画面

gem 'vite_rails'          # vite
# gem 'tailwindcss-rails'   # tailwindcss viteを使うので不要

group :development, :test do
  gem "rspec-rails"       # テストフレームワーク
  gem "factory_bot_rails" # テストデータ生成（fixture代替）
  gem "faker"             # ダミーデータ生成
  gem "gimei"             # 日本用ダミーデータ
  gem "pry-rails"         # デバッグ用（byebug代替）
  
  # pry用
  gem "pry-byebug", group: [:development, :test]  # ステップ実行できるように
  gem "pry-nav", group: [:development, :test]     # next / step / finish の強化
end

group :development do
  gem "rubocop", require: false                # Linter
  gem "rubocop-rails", require: false          # Rails用の拡張
  gem "bullet"                                 # N+1検出
  gem "rack-mini-profiler"                     # ページごとの処理時間可視化
  gem "annotate"                               # モデルにスキーマ情報をコメントで追記
end
